### ISSUE TITLE
[Bug]: Error compiling array of functions

### ISSUE THREAD

**Issue by hsemenenko** [Quantinuum/guppylang#2036]
### Description

The following program seems to compile on [v0.21](https://play.guppylang.org?guppy=fac8fc73-754d-56bc-dbde-52f83c5957a1&utm_source=sharing) but errors on `v1`.
```python
from guppylang import guppy
from guppylang.std.quantum import x, y, z
from guppylang.std.builtins import array

@guppy
def main() -> None:
    paulis = array(x,y,z)
```

```
5 | @guppy
6 | def main() -> None:
7 |     paulis = array(x,y,z)
  |                      ^ Expected expression of type `def x(q: qubit) -> None`, got
  |                        `def y(q: qubit) -> None`

Guppy compilation failed due to 1 previous error
```

### Environment

```markdown

```

**Comment by nicolaassolini-qntm** [comment]
We should solve this bug by making the compiler infer `paulis` as an array of `Function` and not `Unitariy`
