### ISSUE TITLE
[Bug]: Regression for using dataclasses inside struct comptime contexts

### ISSUE THREAD

**Issue by maximilianruesch** [Quantinuum/guppylang#1816]
### Description

The following program compiles with `guppylang-v1.0.0-a0` but does not compile with `guppylang-v1.0.0-a1`:
```python
from guppylang.std.quantum import discard
from guppylang import guppy, array, qubit, comptime
from dataclasses import dataclass

@dataclass
class Config:
    size: int

config = Config(size=5)

@guppy.struct
class Struct:
    qs: array[qubit, comptime(config.size)]

@guppy
def main() -> None:
    s = Struct(array(qubit() for _ in range(comptime(config.size))))
    for q in s.qs:
        discard(q)

main.compile()
```
For the latter, it instead gives
```
Error: Expected a module (at <In[1]>:13:30)
   | 
11 | @guppy.struct
12 | class Struct:
13 |     qs: array[qubit, comptime(config.size)]
   |                               ^^^^^^ Expected a module

Guppy compilation failed due to 1 previous error
```

### Expected Behaviour

There should be no regression.

### Actual Behaviour

There is a regression.

### Environment

```markdown

```

### Additional Context

Following a git bisect, the commit 96dfb01edc3df0b3b9c70499f4b0dc23da80d022 has been identified as the first bad commit, introduced by PR #1809. This is likely to be the culprit, since it modified struct validation, and there may have been accidental changes. A regression test case should be added.
